project:
  type: book
#  output-dir: docs

execute: 
  freeze: auto
  
lang: en


book:
  title: "Fundamentals of Linear Models 2025-2026: Workbook"
  subtitle: "Workbook"
  author: "Dr. Leticia Pablos Robles"
  reader-mode: true
  
  page-footer: 
    left: |
       Fundamentals of Linear Models Workbook was written by Dr. Leticia Pablos Robles
    right: |
      This workbook was built with <a href="https://quarto.org/">Quarto</a>.
  
  cover-image: images/Stats_Ling_Cover_1ed.jpg
  favicon: images/Stats_Ling_Cover_1ed.jpg
  date: "08/30/2025"
  
  chapters:
    - index.qmd
    
    #- preface-1e.qmd
    - intro.qmd
    
    - part: Workgroup1.qmd
      chapters: 
        - intro_to_r.qmd
        - using_libraries.qmd
        - read_data.qmd
        - tidyverse_intro.qmd
        - using_notebooks.qmd
        - assignment1_key.qmd 
        
    - part: Workgroup2.qmd
      chapters:
        - data_organization.qmd
        - data_visualization.qmd
        - descriptive_stats.qmd
        - assignment2_key.qmd

        
    - part: Workgroup3.qmd
      chapters:
         - plot_xy.qmd
         - correlation.qmd
         - lm_intro.qmd
         - assignment3_key.qmd

        
    - part: Workgroup4.qmd
      chapters: 
         - model_fit.qmd
         - model_comparison.qmd
         - model_assumptions.qmd
         - model_categorical.qmd
         - model_reporting1.qmd
         - assignment4_key.qmd
      #   - using_libraries.qmd
      #   - tidyverse_intro.qmd
      #   - read_data.qmd
    
    - part: Workgroup5.qmd
      chapters: 
         - model_multiple.qmd
         - model_posthoc.qmd
         - model_multiple2.qmd
         - assignment5_key.qmd
      #   - using_libraries.qmd
      #   - tidyverse_intro.qmd
      #   - read_data.qmd
        
    - part: Workgroup6.qmd
      #chapters:
      #    - model_interactions.qmd
      #    - model_contrasts.qmd
      #    - model_vif.qmd
      #   - intro_to_r.qmd
      #   - using_libraries.qmd
      #   - tidyverse_intro.qmd
      #   - read_data.qmd

    #- summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    #cover-image: images/UL_logo.jpg
    code-link: true
  
    author-meta: "Dr. Leticia Pablos Robles"
    callout-apperance: simple
    
  # pdf:
  #   titlepage-pdf:
  #     coverpage: true
  #     documentclass: scrreprt
  #     
  # epub:
  #   cover-image: images/Stats_Ling_Cover_1ed.jpg
editor: visual

